# pytorch_lightning==1.8.6
seed_everything: 4444

data:
  class_path: vocos.dataset.VocosDataModule
  init_args:
    train_params:
      filelist_path: /data3/tansongbin/audiobandextension/datasets/SELFDATA/filelist_outline_7.train
      sampling_rate: 16000
      num_samples: 48000
      batch_size: 4
      num_workers: 0

    val_params:
      filelist_path: /data3/tansongbin/audiobandextension/datasets/SELFDATA/filelist_outline_6.val
      sampling_rate: 16000
      num_samples: 24000
      batch_size: 1
      num_workers: 0

model:
  class_path: vocos.experiment.VocosExp
  init_args:
    sample_rate: 16000
    initial_learning_rate: 5.0e-4
    mel_loss_coeff: 45
    mrd_loss_coeff: 0.1
    num_warmup_steps: 0 # Optimizers warmup steps
    pretrain_mel_steps: 0  # 0 means GAN objective from the first iteration

    # automatic evaluation
    evaluate_utmos: true
    evaluate_pesq: true
    evaluate_periodicty: true
    load_pretrain: false
    # ckpt_path: /data3/tansongbin/vocoder_projects/my_vocosfinetune/logs/lightning_logs/version_0/checkpoints/vocos_checkpoint_epoch=129_step=488020_val_loss=4.9799.ckpt

    feature_extractor:
      class_path: vocos.feature_extractors.SpectrogramFeatures
      init_args:
        n_fft: 16
        hop_length: 5
        padding: center
    
    backbone:
      class_path: vocos.models.VocosBackbone
      init_args:
        input_channels: 9
        dim: 256
        intermediate_dim: 768
        num_layers: 8

    head:
      class_path: vocos.heads.ISTFTHead
      init_args:
        dim: 256
        n_fft: 16
        hop_length: 5
        padding: center

trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      name: vocos_spec/
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 200
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        filename: vocos_checkpoint_{epoch}_{step}_{val_loss:.4f}
        save_top_k: 5
        save_last: true
    - class_path: vocos.helpers.GradNormCallback

  # Lightning calculates max_steps across all optimizer steps (rather than number of batches)
  # This equals to 1M steps per generator and 1M per discriminator
  max_steps: 2000000
  # You might want to limit val batches when evaluating all the metrics, as they are time-consuming
  limit_val_batches: 100
  accelerator: gpu
  strategy: ddp
  devices: [0,1,2,3]
  log_every_n_steps: 100

